
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: /home/ziggi/rapp4bw/app/db/development.sqlite3

test:
  <<: *default
  database: /home/ziggi/rapp4bw/app/db/test.sqlite3

production:
  <<: *default
  database: /home/ziggi/rapp4bw/app/db/production.sqlite3
#  adapter: postgresql
#  encoding: unicode
#  database: rap2
#  pool: 5
#  username: rap2
#  password: password
